name: Deploy to GCP Cloud Run & Artifacts

on:
  push:
    branches: [ "infra/deploy-to-cloudrun" ]

jobs:

    deploy:

        runs-on: ubuntu-latest
        env:
          IMAGE_NAME_WEBAPP: us-east1-docker.pkg.dev/${{ secrets.OAUI_GCP_PROJECT_ID }}/gcf-artifacts/${{ secrets.OAUI_GCP_APP_NAME }}_webapp
          REGION: us-east1
          GAR_LOCATION: us-east1-docker.pkg.dev/${{ secrets.OAUI_GCP_PROJECT_ID }}/gcf-artifacts
        steps:

        - name: 'gcloud auth'
          id: 'auth'
          uses: 'google-github-actions/auth@v1'
          with:
            credentials_json: '${{ secrets.OAUI_GCP_CREDENTIALS }}'

        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v1'
  
        - name: GCloud Docker auth
          run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build restapi docker image
          run: docker build -f ${GITHUB_WORKSPACE}/Dockerfile -t $IMAGE_NAME_WEBAPP:$GITHUB_SHA ${GITHUB_WORKSPACE}

        - name: Push webapp docker image
          run: docker push $IMAGE_NAME_WEBAPP:$GITHUB_SHA

        # - name: Deploy restapi docker image
        #   run: gcloud run deploy ${{ secrets.GCP_APP_NAME }}_webapp --image=$IMAGE_NAME_WEBAPP:$GITHUB_SHA --region=us-central1 --project=${{ secrets.OAUI_GCP_PROJECT_ID }}
